IF NOT EXISTS (SELECT name 
           FROM master.sys.databases 
           WHERE name = N'NewsEntities')
BEGIN
	CREATE DATABASE NewsEntities;
END
IF EXISTS (SELECT name 
           FROM master.sys.databases 
           WHERE name = N'NewsEntities')
BEGIN
	ALTER DATABASE [NewsEntities]
	COLLATE Cyrillic_General_CI_AS;
END

USE NewsEntities;
GO
IF EXISTS (SELECT name 
           FROM master.sys.databases 
           WHERE name = N'NewsEntities')
BEGIN
CREATE TABLE Users(
	[Id] INT IDENTITY(1,1) NOT NULL,
	AvatarPath NVARCHAR(MAX) NULL,
	UserName NVARCHAR(256) UNIQUE NOT NULL,
	Email NVARCHAR(256) NULL UNIQUE,
	PasswordHash NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_User PRIMARY KEY CLUSTERED (Id ASC)
);

CREATE TABLE Roles(
	Id INT IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(256) NOT NULL UNIQUE,
	CONSTRAINT PK_Role PRIMARY KEY CLUSTERED (Id ASC)
);

CREATE TABLE UserRoles(
	UserId INT FOREIGN KEY REFERENCES dbo.Users(Id) ON DELETE CASCADE NOT NULL,
	RoleId INT FOREIGN KEY REFERENCES dbo.Roles(Id) ON DELETE CASCADE NOT NULL,
	CONSTRAINT PK_UserRoles PRIMARY KEY CLUSTERED ( UserId ASC , RoleId ASC )
	);

CREATE TABLE Articles(
	Id INT IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(256) NOT NULL UNIQUE,
	[Text] NVARCHAR(MAX) NOT NULL,
	NumberOfViews INT DEFAULT (1),
	[State] Bit NOT NULL DEFAULT (0),
	[Date] DATETIME2(7) NOT NULL DEFAULT convert(varchar, getdate(), 120),
	UserId INT FOREIGN KEY REFERENCES dbo.Users(Id) NOT NULL,
	CONSTRAINT PK_Article PRIMARY KEY CLUSTERED (Id ASC)
	);

CREATE TABLE Comments(
	Id INT IDENTITY(1,1) NOT NULL,
	[Text] NVARCHAR(MAX) NOT NULL,
	[State] Bit NOT NULL DEFAULT (0),
	[Date] DATETIME2(7) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES dbo.Users(Id)  NOT NULL,
	ArticleId INT FOREIGN KEY REFERENCES dbo.Articles(Id) ON DELETE CASCADE  NOT NULL,
	CONSTRAINT PK_Comment PRIMARY KEY CLUSTERED (Id ASC)
	);

CREATE TABLE FileData(
	Id INT IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
	[Path] NVARCHAR(256) NOT NULL UNIQUE,
	[Rank] NVARCHAR(256) NOT NULL,
	ArticleId INT FOREIGN KEY REFERENCES dbo.Articles(Id) ON DELETE CASCADE NOT NULL
	CONSTRAINT PK_File PRIMARY KEY CLUSTERED (Id ASC)
);

CREATE TABLE HashTags(
	Id INT IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(48) NOT NULL UNIQUE,
	CONSTRAINT PK_HashTag PRIMARY KEY CLUSTERED (Id ASC)
);

CREATE TABLE ArticleHashTags(
	ArticleId INT FOREIGN KEY REFERENCES dbo.Articles(Id) ON DELETE CASCADE NOT NULL,
	HashTagId INT FOREIGN KEY REFERENCES dbo.HashTags(Id) ON DELETE CASCADE NOT NULL,
	CONSTRAINT PK_ArticlesHashTags PRIMARY KEY CLUSTERED (ArticleId ASC,HashTagId ASC)
);

CREATE TABLE ReplyToComments(
	CommentId INT FOREIGN KEY REFERENCES dbo.Comments(Id) ON DELETE CASCADE NOT NULL,
	ReplyToCommentId INT FOREIGN KEY REFERENCES dbo.Comments(Id) NOT NULL
	CONSTRAINT PK_ReplyToComment PRIMARY KEY CLUSTERED (CommentId ASC,ReplyToCommentId ASC)
);
END